src/Entity/Profile.php
<?php

namespace App\Entity;

use App\Repository\ProfileRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProfileRepository::class)
 */
class Profile
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $birthday;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $sex;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=500)
     */
    private $presentation;

    /**
     * @ORM\OneToOne(targetEntity=User::class, mappedBy="profile", cascade={"persist", "remove"})
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getSex(): ?string
    {
        return $this->sex;
    }

    public function setSex(string $sex): self
    {
        $this->sex = $sex;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPresentation(): ?string
    {
        return $this->presentation;
    }

    public function setPresentation(string $presentation): self
    {
        $this->presentation = $presentation;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        // unset the owning side of the relation if necessary
        if ($user === null && $this->user !== null) {
            $this->user->setProfile(null);
        }

        // set the owning side of the relation if necessary
        if ($user !== null && $user->getProfile() !== $this) {
            $user->setProfile($this);
        }

        $this->user = $user;

        return $this;
    }
}

src/Form/ProfileType.php
<?php

namespace App\Form;

use App\Entity\Profile;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProfileType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('birthday', DateType::class,['widget' => 'single_text'])
            ->add('sex' , ChoiceType::class,[
                'choices'=>[
                    'Man'=>"Man",
                    'Woman'=>"Woman",
                ],
            ])
            ->add('postal_code')
            ->add('city')
            ->add('presentation')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Profile::class,
        ]);
    }
}

src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\Picture;
use App\Entity\Profile;
use App\Entity\User;
use App\Form\PictureType;
use App\Form\ProfileType;
use App\Repository\ProfileRepository;
use claviska\SimpleImage;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
use Symfony\Component\Security\Guard\Token\PostAuthenticationGuardToken;
use Symfony\Component\String\ByteString;

class ProfileController extends AbstractController
{



    /**
     * @Route ("/profile/create/pic", name="profile_pic")
     */
    public function pic(EntityManagerInterface $entityManager, Request $request){
        $picture = new Picture();
        $formPicture = $this->createForm(PictureType::class, $picture);
        $formPicture->handleRequest($request);

        if ($formPicture->isSubmitted() && $formPicture->isValid()){
            /**@var UploadedFile $uploadedFile*/
            $uploadedFile = $formPicture->get('pic')->getData();

            $newFileName = ByteString::fromRandom(30).".".$uploadedFile->guessExtension();
            try {
                //upload_dir est configuré dans services.yaml
                $uploadedFile->move($this->getParameter('upload_dir'), $newFileName);
            } catch (\Exception $e){
                dd($e->getMessage());
            }

            $simpleImage = new SimpleImage();
            $simpleImage->fromFile($this->getParameter('upload_dir')."/$newFileName")
                        ->bestFit(300, 300)
                        ->toFile($this->getParameter('upload_dir')."/small/$newFileName");

            $picture->setDateCreated(new \DateTime());
            $picture->setFileName($newFileName);

            /** @var User $user */
            $user = $this->getUser();
            $user->setFirstPicture($picture);


            $entityManager->persist($picture);
            $entityManager->flush();

            $this->addFlash('success', 'You are beautiful !');
            return $this->redirectToRoute("main_home");
        }

        return $this->render('profile/pic.html.twig', [
            "picForm"=>$formPicture->createView()
        ]);
    }



    /**
     * @IsGranted ("ROLE_USER_NOT_PROFILED")
     * @Route("/profile/create", name="profile_create")
     */
    public function create(Request $request, EntityManagerInterface $entityManager, TokenStorageInterface $tokenStorage): Response
    {
        /** @var User $user*/
        $user=$this->getUser();
        if($user->getProfile()){
            $profile=$user->getProfile();
        }else{
            $profile = new Profile();
        }
        $form = $this->createForm(ProfileType::class, $profile);
        $form->handleRequest($request);
        if($form->isSubmitted()&&$form->isValid()){
            $profile->setUser($user);
            $user->setRoles(['ROLE_USER']);
            //todo Censurer les gros mots
            $entityManager->persist($profile);
            $entityManager->flush();
            //reconnecter l'utilisateur
            //on recrée une token pour l'utilisateur, sinon il est déconnecté !
            $token = new PostAuthenticationGuardToken($user, 'main', $user->getRoles());
            $tokenStorage->setToken($token);
            $this->addFlash("success", "You have filled up your profile successfully!");
            return $this->redirectToRoute("profile_pic");
        }
        return $this->render('profile/create.html.twig', [
            "profileForm"=>$form->createView()
        ]);
    }



    /**
     * @IsGranted("ROLE_USER")
     * @Route ("/profile/{id}", name="profile_detail", requirements={"id": "\d+"})
     */
    public function detail(Request $request, ProfileRepository $profileRepository, EntityManagerInterface $entityManager): Response{
        /** @var User $user */
        $user = $this->getUser();
        $profile = $profileRepository->find($user->getProfile()->getId());
        if (!$profile){
            throw $this->createNotFoundException('This profile don\'t exist! ');
        }
        return $this->render('profile/detail.html.twig', ["profile"=>$profile]);
    }


}

templates/profile/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello!{% endblock %}

{% block body %}
    <div class="container ">
        <h2>Your profile</h2>
        {{form_start(profileForm) }}
        {{form_row(profileForm.birthday) }}
        {{form_row(profileForm.sex) }}
        {{form_row(profileForm.postal_code) }}
        {{form_row(profileForm.city) }}
        {{form_row(profileForm.presentation) }}
        <div class="field is-grouped">
            <button class="mx-5 button btn-outline-success">Submit</button>
            <button class="button btn-outline-danger">Cancel</button>
        </div>
        {{form_end(profileForm) }}
    </div>
{% endblock %}

templates/profile/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}
Profile of {{ app.user.username }}
{% endblock %}

{% block body %}
<div class="container">
    <h2>{{ app.user.username }}</h2>
        {% if app.user.firstPicture %}
            <p><img src="{{ asset('img/profile/small/'~app.user.firstPicture.fileName) }}" class="img-thumbnail w-25" alt="Photo de profil"></p>
            <p><a href="{{ path('profile_pic') }}" class="btn btn-outline-warning">Modify your photo</a> </p>
        {% else %}
            <p><a href="{{ path('profile_pic') }}" class="btn btn-outline-warning">Share your photo</a> </p>
        {% endif %}

        <table class="table">
            <tbody>
        <tr>
            <th scope="row">Birthday</th>
            <td>{{ profile.birthday|date("d-m-Y") }}</td>
        </tr>
        <tr>
            <th scope="row">Sex</th>
            <td>{{ profile.sex }}</td>
        </tr>
        <tr>
            <th scope="row">Postal_code</th>
            <td>{{ profile.postalCode }}</td>
        </tr>
        <tr>
            <th scope="row">City</th>
            <td>{{ profile.city }}</td>
        </tr>
        <tr>
            <th scope="row">Presentation</th>
            <td>{{ profile.presentation }}</td>
        </tr>
        </tbody>
    </table>
    <a href="{{ path('profile_create') }}" class="btn btn-outline-warning">Modify your information</a>
</div>
{% endblock %}

templates/profile/pic.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container ">
        <h2>Add picture</h2>

        {{ form(picForm) }}

    </div>
{% endblock %}

{% block title %}
    Picture
{% endblock %}